In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

from scenario import Scenario

import openpyxl as op

In [8]:
# Settings :

# from light_sim.ipynb
# Settings angles
#####
start_angle = -60
end_angle = 60
step_angle = 5
angles = np.arange(start_angle, end_angle + 1, step_angle)
# angles = [-60]
print(list(angles))
titres_colonnes = np.append(angles, np.array("temoin", dtype=object), axis=None)

# Annual parameters
###### # from light_sim.ipynb

######
# Settings, year and hours
start_date = pd.Timestamp('2023-01-01')  # Start of the year (avoid leap year)

output_path = "bdd_irr/step60_classic_HBmethod.xlsx"

[-60, -55, -50, -45, -40, -35, -30, -25, -20, -15, -10, -5, 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60]


Import scenario :
1 = True = Backtracking (productible max)
0 = False = Effacement (irradiance au sol maximum)

In [6]:
## TESTS ##
# Instancier des objets scénarios
s_10pc = Scenario(file_path="scenarios/sc_10%.xlsx")
s_full_BT = Scenario(file_path="scenarios/sc_full_BT.xlsx")
# print(s1.scenario[:,:])

In [7]:
print(s_10pc)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


Import bdd_irr

In [13]:
df3 = pd.read_excel(output_path)
print(df3[0:24])

   Month-Day-Hour  -60  -55  -50  -45  -40  -35  -30  -25  -20  ...   15   20  \
0        01-01-00    0    0    0    0    0    0    0    0    0  ...    0    0   
1        01-01-01    0    0    0    0    0    0    0    0    0  ...    0    0   
2        01-01-02    0    0    0    0    0    0    0    0    0  ...    0    0   
3        01-01-03    0    0    0    0    0    0    0    0    0  ...    0    0   
4        01-01-04    0    0    0    0    0    0    0    0    0  ...    0    0   
5        01-01-05    0    0    0    0    0    0    0    0    0  ...    0    0   
6        01-01-06    0    0    0    0    0    0    0    0    0  ...    0    0   
7        01-01-07    0    0    0    0    0    0    0    0    0  ...    0    0   
8        01-01-08   12   12   12   11   11   11   11   10   10  ...    9    9   
9        01-01-09   28   31   32   34   33   33   33   32   31  ...   24   24   
10       01-01-10   45   47   48   52   51   50   49   51   46  ...   34   34   
11       01-01-11   70   72 

Création tab_1

In [45]:
n_rows = 8760

# Création d'un DataFrame avec des valeurs par défaut (par exemple, 0)
tab_1 = pd.DataFrame({
    'hoys': df3['month_day_hour'],   #Hours of the Year
    'effacement': np.ones(n_rows),   #Panel priority mode, 1 = priority to photoovltaic production
    'angle': np.zeros(n_rows),
    'irradiance_sol': np.zeros(n_rows)
})


Import PVSyst

In [46]:
# Chemin vers le fichier Excel
file_path = 'PIOLENC_PVSyst_output.xlsm'

# Nom de l'onglet à lire
sheet_names = ['Tests','Illim']

# Lire l'onglet spécifique
pvsyst = pd.read_excel(file_path, sheet_name=sheet_names)

In [47]:
pvsyst_illim = pvsyst['Illim'].drop(index=list(range(12))).drop(columns=['Unnamed: 4', 'Unnamed: 5']).reset_index(drop=True)
pvsyst_illim.columns = ['Date','E_Grid','PR','PhiAng']
print(pvsyst_illim)

                     Date  E_Grid PR PhiAng
0     1990-01-01 00:00:00 -0.0132  0      0
1     1990-01-01 01:00:00 -0.0132  0      0
2     1990-01-01 02:00:00 -0.0132  0      0
3     1990-01-01 03:00:00 -0.0132  0      0
4     1990-01-01 04:00:00 -0.0132  0      0
...                   ...     ... ..    ...
8755  1990-12-31 19:00:00 -0.0132  0      0
8756  1990-12-31 20:00:00 -0.0132  0      0
8757  1990-12-31 21:00:00 -0.0132  0      0
8758  1990-12-31 22:00:00 -0.0132  0      0
8759  1990-12-31 23:00:00 -0.0132  0      0

[8760 rows x 4 columns]


In [48]:
pvsyst_tests = pvsyst['Tests'].drop(index=list(range(12))).drop(columns=pvsyst['Tests'].columns[4:]).reset_index(drop=True)
pvsyst_tests.columns = ['Date', 'PhiAng', 'E_Grid_SunTrack', 'Egrid Effectif']
print(pvsyst_tests)

                     Date PhiAng E_Grid_SunTrack Egrid Effectif
0     1990-01-01 00:00:00      0         -0.0132              1
1     1990-01-01 01:00:00      0         -0.0132              1
2     1990-01-01 02:00:00      0         -0.0132              1
3     1990-01-01 03:00:00      0         -0.0132              1
4     1990-01-01 04:00:00      0         -0.0132              1
...                   ...    ...             ...            ...
8755  1990-12-31 19:00:00      0         -0.0132             12
8756  1990-12-31 20:00:00      0         -0.0132             12
8757  1990-12-31 21:00:00      0         -0.0132             12
8758  1990-12-31 22:00:00      0         -0.0132             12
8759  1990-12-31 23:00:00      0         -0.0132             12

[8760 rows x 4 columns]


Remplir le tab_1 :

In [49]:
# Remplissage de la colonne 'effacement'
# Parcourir scénario, pour chaque case 0 (False), changer les 1 (panneaux en suntracking) de la colonne 'effacement' en 0 (panneaux effacés)

for i in range(s_10pc.scenario.shape[0]) :  # Pour chaque ligne
    for j in range(s_10pc.scenario.shape[1]) :  # Pour chaque colonne
        if s_10pc.scenario[i,j] == False :
            tab_1.loc[(tab_1['hoys'].dt.hour == j) & (tab_1['hoys'].dt.month == i+1), 'effacement'] = 0

In [52]:
# Remplissage de la colonne 'angle'
# Parcourir tableau_1, en fonction de 'effacement', remplir 'angle' et 'irradiance'
for i in range(tab_1.shape[0]) :
    if tab_1.at[i,'effacement'] == 0:
        #aller chercher irradiance au sol maximum dans tab_final (df3 dans ce .ipynb), et retrouver l'angle correspondant (nom de colonne)
        tab_1.loc[i,'irradiance_sol'] = df3.drop(columns=['month_day_hour','temoin']).iloc[i].max() # Irradiance max
        tab_1.loc[i,'angle'] = df3.drop(columns=['month_day_hour','temoin']).iloc[i].idxmax() # Colonne dont l'irradiance est max
        # /!\ Si égalité entre plusieurs angles, va choisir l'angle le moins élevé (-60 à priori)
    else: #'effacement' == 1
        # pvsyst_illim.loc[...] = angle PVSYST optimal, arrondir, puis trouver irradiance au sol correspondante
        tab_1.loc[i,'irradiance_sol'] = df3.at[i,round(pvsyst_illim.loc[i,'PhiAng']/step_angle)*step_angle]
        tab_1.loc[i,'angle'] = round(pvsyst_illim.loc[i,'PhiAng']/step_angle)*step_angle

# Add control values to tab_1 :

tab_1['temoin'] = df3.loc[:,'temoin']
# Tableau_1 rempli, il ne reste qu'à calculer les rapports entre zone témoin /!\(à intégrer)/!\ et zone d'étude
  

In [66]:
tab_1[0:24]

hoys  effacement  angle  irradiance_sol    temoin
0  2023-01-01 00:00:00         1.0    0.0        0.000000  0.000000
1  2023-01-01 01:00:00         1.0    0.0        0.000000  0.000000
2  2023-01-01 02:00:00         1.0    0.0        0.000000  0.000000
3  2023-01-01 03:00:00         1.0    0.0        0.000000  0.000000
4  2023-01-01 04:00:00         1.0    0.0        0.000000  0.000000
5  2023-01-01 05:00:00         1.0    0.0        0.000000  0.000000
6  2023-01-01 06:00:00         1.0    0.0        0.000000  0.000000
7  2023-01-01 07:00:00         1.0    0.0        0.001722  0.002280
8  2023-01-01 08:00:00         1.0   -5.0        0.009449  0.012313
9  2023-01-01 09:00:00         1.0  -15.0        0.021566  0.026178
10 2023-01-01 10:00:00         1.0  -40.0        0.036984  0.042017
11 2023-01-01 11:00:00         1.0  -40.0        0.062845  0.083053
12 2023-01-01 12:00:00         1.0  -10.0        0.120477  0.161835
13 2023-01-01 13:00:00         1.0   25.0        0.207883  0.222499
14 2023-01-01 14:00:00         1.0   50.0        0.074392  0.196503
15 2023-01-01 15:00:00         1.0   20.0        0.093167  0.101655
16 2023-01-01 16:00:00         1.0    5.0        0.017158  0.022918
17 2023-01-01 17:00:00         1.0    0.0        0.000000  0.000000
18 2023-01-01 18:00:00         1.0    0.0        0.000000  0.000000
19 2023-01-01 19:00:00         1.0    0.0        0.000000  0.000000
20 2023-01-01 20:00:00         1.0    0.0        0.000000  0.000000
21 2023-01-01 21:00:00         1.0    0.0        0.000000  0.000000
22 2023-01-01 22:00:00         1.0    0.0        0.000000  0.000000
23 2023-01-01 23:00:00         1.0    0.0        0.000000  0.000000

In [35]:
# tab_1.to_excel("step5_semitransp_10%.xlsx", index=False, header=True)

Calcul liste de taille 365 concernant rapport de irradiance_zone_témoin sur irradiance_zone_étude

In [67]:
df_daily = tab_1.groupby(tab_1['hoys'].dt.date)['irradiance_sol','temoin'].sum().reset_index()

df_daily.columns = ['date', 'irradiance_sol_day','temoin_day']
print(df_daily)

           date  irradiance_sol_day  temoin_day
0    2023-01-01            0.645644    0.871252
1    2023-01-02            0.324559    0.415251
2    2023-01-03            1.050197    1.295170
3    2023-01-04            2.517704    3.137864
4    2023-01-05            2.811059    3.467914
..          ...                 ...         ...
360  2023-12-27            2.504803    3.308104
361  2023-12-28            0.593889    0.765175
362  2023-12-29            2.021913    2.567961
363  2023-12-30            2.692507    3.501543
364  2023-12-31            2.705956    3.343441

[365 rows x 3 columns]


c:\Users\maceo.valente\.virtualenvs\TSAgriPV-XqNYGekU\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.


In [75]:
#Export to an excel the daily ratio between control radiation and study-zone radiation

daily_ratio = df_daily['irradiance_sol_day']/df_daily['temoin_day']
# daily_ratio.to_excel('daily_ratio_rad.xlsx',header=False,index=False)
print(daily_ratio)

#Daily_ratio are to be multiplied with the Rad column of the climate STICS files

0      0.741054
1      0.781598
2      0.810856
3      0.802363
4      0.810591
         ...   
360    0.757172
361    0.776148
362    0.787361
363    0.768949
364    0.809333
Length: 365, dtype: float64


ChatGPT answer :